// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var AddandremovefrombookmarkprompttemplateServerList = []string{
	"http://127.0.0.1:8000/api",
}

type AddandremovefrombookmarkprompttemplateRequest struct {
	TemplateID int `queryParam:"style=form,explode=true,name=template_id"`
	UserID     int `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *AddandremovefrombookmarkprompttemplateRequest) GetTemplateID() int {
	if o == nil {
		return 0
	}
	return o.TemplateID
}

func (o *AddandremovefrombookmarkprompttemplateRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

// AddandremovefrombookmarkprompttemplateNewRequest1 - OK
type AddandremovefrombookmarkprompttemplateNewRequest1 struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

func (o *AddandremovefrombookmarkprompttemplateNewRequest1) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *AddandremovefrombookmarkprompttemplateNewRequest1) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type AddandremovefrombookmarkprompttemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// OK
	NewRequest1 *AddandremovefrombookmarkprompttemplateNewRequest1
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *AddandremovefrombookmarkprompttemplateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AddandremovefrombookmarkprompttemplateResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *AddandremovefrombookmarkprompttemplateResponse) GetNewRequest1() *AddandremovefrombookmarkprompttemplateNewRequest1 {
	if o == nil {
		return nil
	}
	return o.NewRequest1
}

func (o *AddandremovefrombookmarkprompttemplateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AddandremovefrombookmarkprompttemplateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
