// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var CreateFolderServerList = []string{
	"http://127.0.0.1:8000/api",
}

type CreateFolderRequest struct {
	FolderName string `queryParam:"style=form,explode=true,name=folder_name"`
	UserID     int    `queryParam:"style=form,explode=true,name=user_id"`
	WorkbookID int    `queryParam:"style=form,explode=true,name=workbook_id"`
}

func (o *CreateFolderRequest) GetFolderName() string {
	if o == nil {
		return ""
	}
	return o.FolderName
}

func (o *CreateFolderRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *CreateFolderRequest) GetWorkbookID() int {
	if o == nil {
		return 0
	}
	return o.WorkbookID
}

type CreateFolderCreateFolderliveData3 struct {
	CreatedAt   string  `json:"created_at"`
	Description *string `json:"description"`
	Icon        string  `json:"icon"`
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	UpdatedAt   string  `json:"updated_at"`
	UserID      string  `json:"user_id"`
	WorkbookID  string  `json:"workbook_id"`
}

func (o *CreateFolderCreateFolderliveData3) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *CreateFolderCreateFolderliveData3) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateFolderCreateFolderliveData3) GetIcon() string {
	if o == nil {
		return ""
	}
	return o.Icon
}

func (o *CreateFolderCreateFolderliveData3) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *CreateFolderCreateFolderliveData3) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateFolderCreateFolderliveData3) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *CreateFolderCreateFolderliveData3) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

func (o *CreateFolderCreateFolderliveData3) GetWorkbookID() string {
	if o == nil {
		return ""
	}
	return o.WorkbookID
}

// CreateFolderCreateFolderlive - OK
type CreateFolderCreateFolderlive struct {
	Data    CreateFolderCreateFolderliveData3 `json:"data"`
	Message string                            `json:"message"`
	Status  string                            `json:"status"`
}

func (o *CreateFolderCreateFolderlive) GetData() CreateFolderCreateFolderliveData3 {
	if o == nil {
		return CreateFolderCreateFolderliveData3{}
	}
	return o.Data
}

func (o *CreateFolderCreateFolderlive) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *CreateFolderCreateFolderlive) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type CreateFolderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	CreateFolderlive *CreateFolderCreateFolderlive
	Headers          map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateFolderResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateFolderResponse) GetCreateFolderlive() *CreateFolderCreateFolderlive {
	if o == nil {
		return nil
	}
	return o.CreateFolderlive
}

func (o *CreateFolderResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *CreateFolderResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateFolderResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
