// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var CustomTemplategenerateServerList = []string{
	"https://taam.ai/api",
}

type CustomTemplategenerateRequest struct {
	Creativity   float64 `queryParam:"style=form,explode=true,name=creativity"`
	Description  string  `queryParam:"style=form,explode=true,name=description"`
	FolderID     int     `queryParam:"style=form,explode=true,name=folder_id"`
	Language     string  `queryParam:"style=form,explode=true,name=language"`
	MaxResults   int     `queryParam:"style=form,explode=true,name=max_results"`
	TemplateCode string  `queryParam:"style=form,explode=true,name=template_code"`
	Text         string  `queryParam:"style=form,explode=true,name=text"`
	Text2        string  `queryParam:"style=form,explode=true,name=text2"`
	Title        string  `queryParam:"style=form,explode=true,name=title"`
	UserID       int     `queryParam:"style=form,explode=true,name=user_id"`
	Words        int     `queryParam:"style=form,explode=true,name=words"`
	WorkbookID   int     `queryParam:"style=form,explode=true,name=workbook_id"`
}

func (o *CustomTemplategenerateRequest) GetCreativity() float64 {
	if o == nil {
		return 0.0
	}
	return o.Creativity
}

func (o *CustomTemplategenerateRequest) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *CustomTemplategenerateRequest) GetFolderID() int {
	if o == nil {
		return 0
	}
	return o.FolderID
}

func (o *CustomTemplategenerateRequest) GetLanguage() string {
	if o == nil {
		return ""
	}
	return o.Language
}

func (o *CustomTemplategenerateRequest) GetMaxResults() int {
	if o == nil {
		return 0
	}
	return o.MaxResults
}

func (o *CustomTemplategenerateRequest) GetTemplateCode() string {
	if o == nil {
		return ""
	}
	return o.TemplateCode
}

func (o *CustomTemplategenerateRequest) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}

func (o *CustomTemplategenerateRequest) GetText2() string {
	if o == nil {
		return ""
	}
	return o.Text2
}

func (o *CustomTemplategenerateRequest) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *CustomTemplategenerateRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *CustomTemplategenerateRequest) GetWords() int {
	if o == nil {
		return 0
	}
	return o.Words
}

func (o *CustomTemplategenerateRequest) GetWorkbookID() int {
	if o == nil {
		return 0
	}
	return o.WorkbookID
}

// CustomTemplategenerateCustomTemplategenerate - OK
type CustomTemplategenerateCustomTemplategenerate struct {
	ID          int    `json:"id"`
	MaxResults  string `json:"max_results"`
	MaxWords    int    `json:"max_words"`
	Status      string `json:"status"`
	Temperature string `json:"temperature"`
}

func (o *CustomTemplategenerateCustomTemplategenerate) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *CustomTemplategenerateCustomTemplategenerate) GetMaxResults() string {
	if o == nil {
		return ""
	}
	return o.MaxResults
}

func (o *CustomTemplategenerateCustomTemplategenerate) GetMaxWords() int {
	if o == nil {
		return 0
	}
	return o.MaxWords
}

func (o *CustomTemplategenerateCustomTemplategenerate) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *CustomTemplategenerateCustomTemplategenerate) GetTemperature() string {
	if o == nil {
		return ""
	}
	return o.Temperature
}

type CustomTemplategenerateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	CustomTemplategenerate *CustomTemplategenerateCustomTemplategenerate
	Headers                map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CustomTemplategenerateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CustomTemplategenerateResponse) GetCustomTemplategenerate() *CustomTemplategenerateCustomTemplategenerate {
	if o == nil {
		return nil
	}
	return o.CustomTemplategenerate
}

func (o *CustomTemplategenerateResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *CustomTemplategenerateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CustomTemplategenerateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
