// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var CustomTemplatesServerList = []string{
	"https://taam.ai/api",
}

type CustomTemplatesRequest struct {
	UserID int `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *CustomTemplatesRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

type CustomTemplatesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CustomTemplatesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CustomTemplatesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CustomTemplatesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
