// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var DeleteWorkspaceServerList = []string{
	"https://taam.ai/api",
}

type DeleteWorkspaceRequest struct {
	UserID     int `queryParam:"style=form,explode=true,name=user_id"`
	WorkbookID int `queryParam:"style=form,explode=true,name=workbook_id"`
}

func (o *DeleteWorkspaceRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *DeleteWorkspaceRequest) GetWorkbookID() int {
	if o == nil {
		return 0
	}
	return o.WorkbookID
}

// DeleteWorkspaceDeleteWorkspacelive - OK
type DeleteWorkspaceDeleteWorkspacelive struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

func (o *DeleteWorkspaceDeleteWorkspacelive) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *DeleteWorkspaceDeleteWorkspacelive) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type DeleteWorkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	DeleteWorkspacelive *DeleteWorkspaceDeleteWorkspacelive
	Headers             map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteWorkspaceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteWorkspaceResponse) GetDeleteWorkspacelive() *DeleteWorkspaceDeleteWorkspacelive {
	if o == nil {
		return nil
	}
	return o.DeleteWorkspacelive
}

func (o *DeleteWorkspaceResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *DeleteWorkspaceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteWorkspaceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
