// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var DeleteCustomtemplateServerList = []string{
	"http://127.0.0.1:8000/api",
}

type DeleteCustomtemplateRequest struct {
	TemplateID int `queryParam:"style=form,explode=true,name=template_id"`
	UserID     int `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *DeleteCustomtemplateRequest) GetTemplateID() int {
	if o == nil {
		return 0
	}
	return o.TemplateID
}

func (o *DeleteCustomtemplateRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

// DeleteCustomtemplateDeleteCustomtemplate - OK
type DeleteCustomtemplateDeleteCustomtemplate struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

func (o *DeleteCustomtemplateDeleteCustomtemplate) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *DeleteCustomtemplateDeleteCustomtemplate) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type DeleteCustomtemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	DeleteCustomtemplate *DeleteCustomtemplateDeleteCustomtemplate
	Headers              map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteCustomtemplateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteCustomtemplateResponse) GetDeleteCustomtemplate() *DeleteCustomtemplateDeleteCustomtemplate {
	if o == nil {
		return nil
	}
	return o.DeleteCustomtemplate
}

func (o *DeleteCustomtemplateResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *DeleteCustomtemplateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteCustomtemplateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
