// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var DeleteallkindofdocumentsServerList = []string{
	"http://127.0.0.1:8000/api",
}

// DeleteallkindofdocumentsDeleteallkindofdocuments - OK
type DeleteallkindofdocumentsDeleteallkindofdocuments struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

func (o *DeleteallkindofdocumentsDeleteallkindofdocuments) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *DeleteallkindofdocumentsDeleteallkindofdocuments) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type DeleteallkindofdocumentsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	Deleteallkindofdocuments *DeleteallkindofdocumentsDeleteallkindofdocuments
	Headers                  map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteallkindofdocumentsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteallkindofdocumentsResponse) GetDeleteallkindofdocuments() *DeleteallkindofdocumentsDeleteallkindofdocuments {
	if o == nil {
		return nil
	}
	return o.Deleteallkindofdocuments
}

func (o *DeleteallkindofdocumentsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *DeleteallkindofdocumentsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteallkindofdocumentsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
