// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var FileuploadServerList = []string{
	"https://taam.ai/api",
}

type FileuploadRequestBodyFile struct {
	Content []byte `multipartForm:"content"`
	File    string `multipartForm:"name=file"`
}

func (o *FileuploadRequestBodyFile) GetContent() []byte {
	if o == nil {
		return []byte{}
	}
	return o.Content
}

func (o *FileuploadRequestBodyFile) GetFile() string {
	if o == nil {
		return ""
	}
	return o.File
}

type FileuploadRequestBody struct {
	File FileuploadRequestBodyFile `multipartForm:"file"`
}

func (o *FileuploadRequestBody) GetFile() FileuploadRequestBodyFile {
	if o == nil {
		return FileuploadRequestBodyFile{}
	}
	return o.File
}

type FileuploadResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *FileuploadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *FileuploadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *FileuploadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
