// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var GenerateCodeServerList = []string{
	"http://127.0.0.1:8000/api",
}

type GenerateCodeRequest struct {
	Document     string `queryParam:"style=form,explode=true,name=document"`
	Instructions string `queryParam:"style=form,explode=true,name=instructions"`
	Language     string `queryParam:"style=form,explode=true,name=language"`
	UserID       int    `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *GenerateCodeRequest) GetDocument() string {
	if o == nil {
		return ""
	}
	return o.Document
}

func (o *GenerateCodeRequest) GetInstructions() string {
	if o == nil {
		return ""
	}
	return o.Instructions
}

func (o *GenerateCodeRequest) GetLanguage() string {
	if o == nil {
		return ""
	}
	return o.Language
}

func (o *GenerateCodeRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

// GenerateCodeGenerateCode - OK
type GenerateCodeGenerateCode struct {
	Current int    `json:"current"`
	ID      int    `json:"id"`
	Old     string `json:"old"`
	Status  string `json:"status"`
	Text    string `json:"text"`
}

func (o *GenerateCodeGenerateCode) GetCurrent() int {
	if o == nil {
		return 0
	}
	return o.Current
}

func (o *GenerateCodeGenerateCode) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *GenerateCodeGenerateCode) GetOld() string {
	if o == nil {
		return ""
	}
	return o.Old
}

func (o *GenerateCodeGenerateCode) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *GenerateCodeGenerateCode) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}

type GenerateCodeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	GenerateCode *GenerateCodeGenerateCode
	Headers      map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GenerateCodeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GenerateCodeResponse) GetGenerateCode() *GenerateCodeGenerateCode {
	if o == nil {
		return nil
	}
	return o.GenerateCode
}

func (o *GenerateCodeResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *GenerateCodeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GenerateCodeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
