// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var JoinworkbookrequestrServerList = []string{
	"http://127.0.0.1:8000/api",
}

type JoinworkbookrequestrRequest struct {
	Email      string `queryParam:"style=form,explode=true,name=email"`
	UserID     int    `queryParam:"style=form,explode=true,name=user_id"`
	WorkbookID int    `queryParam:"style=form,explode=true,name=workbook_id"`
}

func (o *JoinworkbookrequestrRequest) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *JoinworkbookrequestrRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *JoinworkbookrequestrRequest) GetWorkbookID() int {
	if o == nil {
		return 0
	}
	return o.WorkbookID
}

// JoinworkbookrequestrJoinworkbookrequestr - OK
type JoinworkbookrequestrJoinworkbookrequestr struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

func (o *JoinworkbookrequestrJoinworkbookrequestr) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *JoinworkbookrequestrJoinworkbookrequestr) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type JoinworkbookrequestrResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// OK
	Joinworkbookrequestr *JoinworkbookrequestrJoinworkbookrequestr
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *JoinworkbookrequestrResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *JoinworkbookrequestrResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *JoinworkbookrequestrResponse) GetJoinworkbookrequestr() *JoinworkbookrequestrJoinworkbookrequestr {
	if o == nil {
		return nil
	}
	return o.Joinworkbookrequestr
}

func (o *JoinworkbookrequestrResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *JoinworkbookrequestrResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
