// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var PdftotextServerList = []string{
	"https://taam.ai/api",
}

type PdftotextRequestBodyFile struct {
	Content []byte `multipartForm:"content"`
	File    string `multipartForm:"name=file"`
}

func (o *PdftotextRequestBodyFile) GetContent() []byte {
	if o == nil {
		return []byte{}
	}
	return o.Content
}

func (o *PdftotextRequestBodyFile) GetFile() string {
	if o == nil {
		return ""
	}
	return o.File
}

type PdftotextRequestBody struct {
	File PdftotextRequestBodyFile `multipartForm:"file"`
}

func (o *PdftotextRequestBody) GetFile() PdftotextRequestBodyFile {
	if o == nil {
		return PdftotextRequestBodyFile{}
	}
	return o.File
}

type PdftotextResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PdftotextResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PdftotextResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PdftotextResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
