// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var PermanentDeletefolderServerList = []string{
	"https://taam.ai/api",
}

type PermanentDeletefolderRequest struct {
	FolderID int `queryParam:"style=form,explode=true,name=folder_id"`
	UserID   int `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *PermanentDeletefolderRequest) GetFolderID() int {
	if o == nil {
		return 0
	}
	return o.FolderID
}

func (o *PermanentDeletefolderRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

type PermanentDeletefolderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PermanentDeletefolderResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PermanentDeletefolderResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PermanentDeletefolderResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
