// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var PermanentDeletedocumentServerList = []string{
	"http://127.0.0.1:8000/api",
}

type PermanentDeletedocumentRequest struct {
	ID     int    `queryParam:"style=form,explode=true,name=id"`
	Type   string `queryParam:"style=form,explode=true,name=type"`
	UserID int    `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *PermanentDeletedocumentRequest) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *PermanentDeletedocumentRequest) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *PermanentDeletedocumentRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

// PermanentDeletedocumentPermanentDeletedocument - OK
type PermanentDeletedocumentPermanentDeletedocument struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

func (o *PermanentDeletedocumentPermanentDeletedocument) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *PermanentDeletedocumentPermanentDeletedocument) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type PermanentDeletedocumentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	PermanentDeletedocument *PermanentDeletedocumentPermanentDeletedocument
}

func (o *PermanentDeletedocumentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PermanentDeletedocumentResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *PermanentDeletedocumentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PermanentDeletedocumentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PermanentDeletedocumentResponse) GetPermanentDeletedocument() *PermanentDeletedocumentPermanentDeletedocument {
	if o == nil {
		return nil
	}
	return o.PermanentDeletedocument
}
