// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var RejectWorkbookServerList = []string{
	"http://127.0.0.1:8000/api",
}

type RejectWorkbookRequest struct {
	UserID     int `queryParam:"style=form,explode=true,name=user_id"`
	WorkbookID int `queryParam:"style=form,explode=true,name=workbook_id"`
}

func (o *RejectWorkbookRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *RejectWorkbookRequest) GetWorkbookID() int {
	if o == nil {
		return 0
	}
	return o.WorkbookID
}

// RejectWorkbookRejectWorkbook - OK
type RejectWorkbookRejectWorkbook struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

func (o *RejectWorkbookRejectWorkbook) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *RejectWorkbookRejectWorkbook) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type RejectWorkbookResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// OK
	RejectWorkbook *RejectWorkbookRejectWorkbook
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *RejectWorkbookResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RejectWorkbookResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *RejectWorkbookResponse) GetRejectWorkbook() *RejectWorkbookRejectWorkbook {
	if o == nil {
		return nil
	}
	return o.RejectWorkbook
}

func (o *RejectWorkbookResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RejectWorkbookResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
