// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var RestoreProductServerList = []string{
	"http://127.0.0.1:8000/api",
}

type RestoreProductRequest struct {
	ProductID int `queryParam:"style=form,explode=true,name=product_id"`
	UserID    int `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *RestoreProductRequest) GetProductID() int {
	if o == nil {
		return 0
	}
	return o.ProductID
}

func (o *RestoreProductRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

// RestoreProductRestoreProduct - OK
type RestoreProductRestoreProduct struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

func (o *RestoreProductRestoreProduct) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *RestoreProductRestoreProduct) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type RestoreProductResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// OK
	RestoreProduct *RestoreProductRestoreProduct
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *RestoreProductResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RestoreProductResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *RestoreProductResponse) GetRestoreProduct() *RestoreProductRestoreProduct {
	if o == nil {
		return nil
	}
	return o.RestoreProduct
}

func (o *RestoreProductResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RestoreProductResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
