// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeServerList = []string{
	"http://127.0.0.1:8000/api",
}

type RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeRequest struct {
	ID     int    `queryParam:"style=form,explode=true,name=id"`
	Type   string `queryParam:"style=form,explode=true,name=type"`
	UserID int    `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeRequest) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeRequest) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

// RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeRestoreDocuemntofalltypecontentVoiceoverimagestranscriptcode - OK
type RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeRestoreDocuemntofalltypecontentVoiceoverimagestranscriptcode struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

func (o *RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeRestoreDocuemntofalltypecontentVoiceoverimagestranscriptcode) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeRestoreDocuemntofalltypecontentVoiceoverimagestranscriptcode) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// OK
	Voiceoverimagestranscriptcode *RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeRestoreDocuemntofalltypecontentVoiceoverimagestranscriptcode
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeResponse) GetVoiceoverimagestranscriptcode() *RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeRestoreDocuemntofalltypecontentVoiceoverimagestranscriptcode {
	if o == nil {
		return nil
	}
	return o.Voiceoverimagestranscriptcode
}

func (o *RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RestoreDocuemntofalltypeContentVoiceoverImagesTranscriptCodeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
