// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var RestorePromptTemplateServerList = []string{
	"http://127.0.0.1:8000/api",
}

type RestorePromptTemplateRequest struct {
	TemplateID int `queryParam:"style=form,explode=true,name=template_id"`
	UserID     int `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *RestorePromptTemplateRequest) GetTemplateID() int {
	if o == nil {
		return 0
	}
	return o.TemplateID
}

func (o *RestorePromptTemplateRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

// RestorePromptTemplateRestorePromptTemplate - OK
type RestorePromptTemplateRestorePromptTemplate struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

func (o *RestorePromptTemplateRestorePromptTemplate) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *RestorePromptTemplateRestorePromptTemplate) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type RestorePromptTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// OK
	RestorePromptTemplate *RestorePromptTemplateRestorePromptTemplate
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *RestorePromptTemplateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RestorePromptTemplateResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *RestorePromptTemplateResponse) GetRestorePromptTemplate() *RestorePromptTemplateRestorePromptTemplate {
	if o == nil {
		return nil
	}
	return o.RestorePromptTemplate
}

func (o *RestorePromptTemplateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RestorePromptTemplateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
