// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var SavetranscriptServerList = []string{
	"http://127.0.0.1:8000/api",
}

type SavetranscriptRequest struct {
	Text             string `queryParam:"style=form,explode=true,name=text"`
	Title            string `queryParam:"style=form,explode=true,name=title"`
	TranscriptID     int    `queryParam:"style=form,explode=true,name=transcript_id"`
	UserID           int    `queryParam:"style=form,explode=true,name=user_id"`
	WorkbookFolderID int    `queryParam:"style=form,explode=true,name=workbook_folder_id"`
	WorkbookID       int    `queryParam:"style=form,explode=true,name=workbook_id"`
}

func (o *SavetranscriptRequest) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}

func (o *SavetranscriptRequest) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *SavetranscriptRequest) GetTranscriptID() int {
	if o == nil {
		return 0
	}
	return o.TranscriptID
}

func (o *SavetranscriptRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *SavetranscriptRequest) GetWorkbookFolderID() int {
	if o == nil {
		return 0
	}
	return o.WorkbookFolderID
}

func (o *SavetranscriptRequest) GetWorkbookID() int {
	if o == nil {
		return 0
	}
	return o.WorkbookID
}

// SavetranscriptSavetranscript - OK
type SavetranscriptSavetranscript struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

func (o *SavetranscriptSavetranscript) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *SavetranscriptSavetranscript) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type SavetranscriptResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// OK
	Savetranscript *SavetranscriptSavetranscript
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SavetranscriptResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SavetranscriptResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *SavetranscriptResponse) GetSavetranscript() *SavetranscriptSavetranscript {
	if o == nil {
		return nil
	}
	return o.Savetranscript
}

func (o *SavetranscriptResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SavetranscriptResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
