// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var SetdefualtworkspaceServerList = []string{
	"https://taam.ai/api",
}

type SetdefualtworkspaceRequest struct {
	UserID     int `queryParam:"style=form,explode=true,name=user_id"`
	WorkbookID int `queryParam:"style=form,explode=true,name=workbook_id"`
}

func (o *SetdefualtworkspaceRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *SetdefualtworkspaceRequest) GetWorkbookID() int {
	if o == nil {
		return 0
	}
	return o.WorkbookID
}

type SetdefualtworkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SetdefualtworkspaceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SetdefualtworkspaceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SetdefualtworkspaceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
