// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var TemplateDetailServerList = []string{
	"https://taam.ai/api",
}

type TemplateDetailRequest struct {
	TemplateID int `queryParam:"style=form,explode=true,name=template_id"`
	UserID     int `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *TemplateDetailRequest) GetTemplateID() int {
	if o == nil {
		return 0
	}
	return o.TemplateID
}

func (o *TemplateDetailRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

type TemplateDetailResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *TemplateDetailResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TemplateDetailResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TemplateDetailResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
