// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var TrashedCustomTemplatesServerList = []string{
	"http://127.0.0.1:8000/api",
}

type TrashedCustomTemplatesRequest struct {
	UserID int `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *TrashedCustomTemplatesRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

// TrashedCustomTemplatesTrashedCustomTemplates - OK
type TrashedCustomTemplatesTrashedCustomTemplates struct {
	Data    []string `json:"data"`
	Message string   `json:"message"`
	Status  string   `json:"status"`
}

func (o *TrashedCustomTemplatesTrashedCustomTemplates) GetData() []string {
	if o == nil {
		return []string{}
	}
	return o.Data
}

func (o *TrashedCustomTemplatesTrashedCustomTemplates) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *TrashedCustomTemplatesTrashedCustomTemplates) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type TrashedCustomTemplatesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TrashedCustomTemplates *TrashedCustomTemplatesTrashedCustomTemplates
}

func (o *TrashedCustomTemplatesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TrashedCustomTemplatesResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *TrashedCustomTemplatesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TrashedCustomTemplatesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TrashedCustomTemplatesResponse) GetTrashedCustomTemplates() *TrashedCustomTemplatesTrashedCustomTemplates {
	if o == nil {
		return nil
	}
	return o.TrashedCustomTemplates
}
