// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/taamai/pkg/models/shared"
	"net/http"
)

var TrashedfoldersServerList = []string{
	"http://127.0.0.1:8000/api",
}

type TrashedfoldersRequest struct {
	UserID     int `queryParam:"style=form,explode=true,name=user_id"`
	WorkbookID int `queryParam:"style=form,explode=true,name=workbook_id"`
}

func (o *TrashedfoldersRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *TrashedfoldersRequest) GetWorkbookID() int {
	if o == nil {
		return 0
	}
	return o.WorkbookID
}

// TrashedfoldersTrashedfolderslive - OK
type TrashedfoldersTrashedfolderslive struct {
	Data    []shared.Data5 `json:"data"`
	Message string         `json:"message"`
	Status  string         `json:"status"`
}

func (o *TrashedfoldersTrashedfolderslive) GetData() []shared.Data5 {
	if o == nil {
		return []shared.Data5{}
	}
	return o.Data
}

func (o *TrashedfoldersTrashedfolderslive) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *TrashedfoldersTrashedfolderslive) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type TrashedfoldersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Trashedfolderslive *TrashedfoldersTrashedfolderslive
}

func (o *TrashedfoldersResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TrashedfoldersResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *TrashedfoldersResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TrashedfoldersResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TrashedfoldersResponse) GetTrashedfolderslive() *TrashedfoldersTrashedfolderslive {
	if o == nil {
		return nil
	}
	return o.Trashedfolderslive
}
