// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

var UploadfileforchatpdfServerList = []string{
	"https://taam.ai/api",
}

type UploadfileforchatpdfRequestBodyFile struct {
	Content []byte `multipartForm:"content"`
	File    string `multipartForm:"name=file"`
}

func (o *UploadfileforchatpdfRequestBodyFile) GetContent() []byte {
	if o == nil {
		return []byte{}
	}
	return o.Content
}

func (o *UploadfileforchatpdfRequestBodyFile) GetFile() string {
	if o == nil {
		return ""
	}
	return o.File
}

type UploadfileforchatpdfRequestBody struct {
	File UploadfileforchatpdfRequestBodyFile `multipartForm:"file"`
}

func (o *UploadfileforchatpdfRequestBody) GetFile() UploadfileforchatpdfRequestBodyFile {
	if o == nil {
		return UploadfileforchatpdfRequestBodyFile{}
	}
	return o.File
}

type UploadfileforchatpdfResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UploadfileforchatpdfResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UploadfileforchatpdfResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UploadfileforchatpdfResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
