// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/taamai/pkg/models/shared"
	"net/http"
)

var UserchatsServerList = []string{
	"https://taam.ai/api",
}

type UserchatsRequest struct {
	Type   string `queryParam:"style=form,explode=true,name=type"`
	UserID int    `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *UserchatsRequest) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *UserchatsRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

// UserchatsUserchats - OK
type UserchatsUserchats struct {
	Count   int             `json:"count"`
	Data    []shared.Data10 `json:"data"`
	Message string          `json:"message"`
	Status  string          `json:"status"`
}

func (o *UserchatsUserchats) GetCount() int {
	if o == nil {
		return 0
	}
	return o.Count
}

func (o *UserchatsUserchats) GetData() []shared.Data10 {
	if o == nil {
		return []shared.Data10{}
	}
	return o.Data
}

func (o *UserchatsUserchats) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *UserchatsUserchats) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type UserchatsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Userchats *UserchatsUserchats
}

func (o *UserchatsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UserchatsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *UserchatsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UserchatsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UserchatsResponse) GetUserchats() *UserchatsUserchats {
	if o == nil {
		return nil
	}
	return o.Userchats
}
