// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/taamai/pkg/models/shared"
	"net/http"
)

var WorkbookimagesServerList = []string{
	"https://taam.ai/api",
}

type WorkbookimagesRequest struct {
	FolderID   int    `queryParam:"style=form,explode=true,name=folder_id"`
	Type       string `queryParam:"style=form,explode=true,name=type"`
	UserID     int    `queryParam:"style=form,explode=true,name=user_id"`
	WorkbookID string `queryParam:"style=form,explode=true,name=workbook_id"`
}

func (o *WorkbookimagesRequest) GetFolderID() int {
	if o == nil {
		return 0
	}
	return o.FolderID
}

func (o *WorkbookimagesRequest) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *WorkbookimagesRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *WorkbookimagesRequest) GetWorkbookID() string {
	if o == nil {
		return ""
	}
	return o.WorkbookID
}

// WorkbookimagesWorkbookimages - OK
type WorkbookimagesWorkbookimages struct {
	Count   int            `json:"count"`
	Data    []shared.Data8 `json:"data"`
	Message string         `json:"message"`
	Status  string         `json:"status"`
}

func (o *WorkbookimagesWorkbookimages) GetCount() int {
	if o == nil {
		return 0
	}
	return o.Count
}

func (o *WorkbookimagesWorkbookimages) GetData() []shared.Data8 {
	if o == nil {
		return []shared.Data8{}
	}
	return o.Data
}

func (o *WorkbookimagesWorkbookimages) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *WorkbookimagesWorkbookimages) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type WorkbookimagesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Workbookimages *WorkbookimagesWorkbookimages
}

func (o *WorkbookimagesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *WorkbookimagesResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *WorkbookimagesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *WorkbookimagesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *WorkbookimagesResponse) GetWorkbookimages() *WorkbookimagesWorkbookimages {
	if o == nil {
		return nil
	}
	return o.Workbookimages
}
