// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/taamai/pkg/models/shared"
	"net/http"
)

var WorkbookpoliciesServerList = []string{
	"https://taam.ai/api",
}

type WorkbookpoliciesRequest struct {
	Type   string `queryParam:"style=form,explode=true,name=type"`
	UserID int    `queryParam:"style=form,explode=true,name=user_id"`
}

func (o *WorkbookpoliciesRequest) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *WorkbookpoliciesRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

// WorkbookpoliciesWorkbookpolicies - OK
type WorkbookpoliciesWorkbookpolicies struct {
	Count   int             `json:"count"`
	Data    []shared.Data11 `json:"data"`
	Message string          `json:"message"`
	Status  string          `json:"status"`
}

func (o *WorkbookpoliciesWorkbookpolicies) GetCount() int {
	if o == nil {
		return 0
	}
	return o.Count
}

func (o *WorkbookpoliciesWorkbookpolicies) GetData() []shared.Data11 {
	if o == nil {
		return []shared.Data11{}
	}
	return o.Data
}

func (o *WorkbookpoliciesWorkbookpolicies) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *WorkbookpoliciesWorkbookpolicies) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type WorkbookpoliciesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Workbookpolicies *WorkbookpoliciesWorkbookpolicies
}

func (o *WorkbookpoliciesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *WorkbookpoliciesResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *WorkbookpoliciesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *WorkbookpoliciesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *WorkbookpoliciesResponse) GetWorkbookpolicies() *WorkbookpoliciesWorkbookpolicies {
	if o == nil {
		return nil
	}
	return o.Workbookpolicies
}
