// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/taamai/pkg/models/shared"
	"net/http"
)

var WorkbookcodesServerList = []string{
	"https://taam.ai/api",
}

type WorkbookcodesRequest struct {
	FolderID   int    `queryParam:"style=form,explode=true,name=folder_id"`
	Type       string `queryParam:"style=form,explode=true,name=type"`
	UserID     int    `queryParam:"style=form,explode=true,name=user_id"`
	WorkbookID string `queryParam:"style=form,explode=true,name=workbook_id"`
}

func (o *WorkbookcodesRequest) GetFolderID() int {
	if o == nil {
		return 0
	}
	return o.FolderID
}

func (o *WorkbookcodesRequest) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *WorkbookcodesRequest) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *WorkbookcodesRequest) GetWorkbookID() string {
	if o == nil {
		return ""
	}
	return o.WorkbookID
}

// WorkbookcodesNewRequest - OK
type WorkbookcodesNewRequest struct {
	Count   int            `json:"count"`
	Data    []shared.Data9 `json:"data"`
	Message string         `json:"message"`
	Status  string         `json:"status"`
}

func (o *WorkbookcodesNewRequest) GetCount() int {
	if o == nil {
		return 0
	}
	return o.Count
}

func (o *WorkbookcodesNewRequest) GetData() []shared.Data9 {
	if o == nil {
		return []shared.Data9{}
	}
	return o.Data
}

func (o *WorkbookcodesNewRequest) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *WorkbookcodesNewRequest) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type WorkbookcodesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// OK
	NewRequest *WorkbookcodesNewRequest
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *WorkbookcodesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *WorkbookcodesResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *WorkbookcodesResponse) GetNewRequest() *WorkbookcodesNewRequest {
	if o == nil {
		return nil
	}
	return o.NewRequest
}

func (o *WorkbookcodesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *WorkbookcodesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
