// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Contentsinworkbook struct {
	Count   int     `json:"count"`
	Data    []Data4 `json:"data"`
	Message string  `json:"message"`
	Status  string  `json:"status"`
}

func (o *Contentsinworkbook) GetCount() int {
	if o == nil {
		return 0
	}
	return o.Count
}

func (o *Contentsinworkbook) GetData() []Data4 {
	if o == nil {
		return []Data4{}
	}
	return o.Data
}

func (o *Contentsinworkbook) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *Contentsinworkbook) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}
