// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Data15 struct {
	CreatedAt    string   `json:"created_at"`
	DeletedAt    *string  `json:"deleted_at"`
	Description  string   `json:"description"`
	Edit         int      `json:"edit"`
	Fields       []string `json:"fields"`
	Group        string   `json:"group"`
	Icon         string   `json:"icon"`
	ID           int      `json:"id"`
	Image        *string  `json:"image"`
	Lang         string   `json:"lang"`
	Name         string   `json:"name"`
	New          int      `json:"new"`
	Package      string   `json:"package"`
	Professional int      `json:"professional"`
	Prompt       *string  `json:"prompt"`
	Public       int      `json:"public"`
	Slug         string   `json:"slug"`
	Status       int      `json:"status"`
	TemplateCode string   `json:"template_code"`
	Tone         int      `json:"tone"`
	Type         string   `json:"type"`
	UpdatedAt    string   `json:"updated_at"`
	UserID       int      `json:"user_id"`
}

func (o *Data15) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *Data15) GetDeletedAt() *string {
	if o == nil {
		return nil
	}
	return o.DeletedAt
}

func (o *Data15) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *Data15) GetEdit() int {
	if o == nil {
		return 0
	}
	return o.Edit
}

func (o *Data15) GetFields() []string {
	if o == nil {
		return []string{}
	}
	return o.Fields
}

func (o *Data15) GetGroup() string {
	if o == nil {
		return ""
	}
	return o.Group
}

func (o *Data15) GetIcon() string {
	if o == nil {
		return ""
	}
	return o.Icon
}

func (o *Data15) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Data15) GetImage() *string {
	if o == nil {
		return nil
	}
	return o.Image
}

func (o *Data15) GetLang() string {
	if o == nil {
		return ""
	}
	return o.Lang
}

func (o *Data15) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Data15) GetNew() int {
	if o == nil {
		return 0
	}
	return o.New
}

func (o *Data15) GetPackage() string {
	if o == nil {
		return ""
	}
	return o.Package
}

func (o *Data15) GetProfessional() int {
	if o == nil {
		return 0
	}
	return o.Professional
}

func (o *Data15) GetPrompt() *string {
	if o == nil {
		return nil
	}
	return o.Prompt
}

func (o *Data15) GetPublic() int {
	if o == nil {
		return 0
	}
	return o.Public
}

func (o *Data15) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *Data15) GetStatus() int {
	if o == nil {
		return 0
	}
	return o.Status
}

func (o *Data15) GetTemplateCode() string {
	if o == nil {
		return ""
	}
	return o.TemplateCode
}

func (o *Data15) GetTone() int {
	if o == nil {
		return 0
	}
	return o.Tone
}

func (o *Data15) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *Data15) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *Data15) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}
