// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Data14 struct {
	BulletPoints   string `json:"bullet_points"`
	DeletedAt      string `json:"deleted_at"`
	Description    string `json:"description"`
	FeatureImage   string `json:"feature_image"`
	ID             int    `json:"id"`
	Name           string `json:"name"`
	Tags           string `json:"tags"`
	TargetAudience string `json:"target_audience"`
	UserID         int    `json:"user_id"`
}

func (o *Data14) GetBulletPoints() string {
	if o == nil {
		return ""
	}
	return o.BulletPoints
}

func (o *Data14) GetDeletedAt() string {
	if o == nil {
		return ""
	}
	return o.DeletedAt
}

func (o *Data14) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *Data14) GetFeatureImage() string {
	if o == nil {
		return ""
	}
	return o.FeatureImage
}

func (o *Data14) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Data14) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Data14) GetTags() string {
	if o == nil {
		return ""
	}
	return o.Tags
}

func (o *Data14) GetTargetAudience() string {
	if o == nil {
		return ""
	}
	return o.TargetAudience
}

func (o *Data14) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}
