// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Data7 struct {
	AudioType        string  `json:"audio_type"`
	CreatedAt        string  `json:"created_at"`
	DeletedAt        *string `json:"deleted_at"`
	Description      *string `json:"description"`
	ExpiresAt        string  `json:"expires_at"`
	FileName         string  `json:"file_name"`
	Format           string  `json:"format"`
	ID               int     `json:"id"`
	Length           string  `json:"length"`
	PlanType         string  `json:"plan_type"`
	Size             string  `json:"size"`
	Storage          string  `json:"storage"`
	Task             string  `json:"task"`
	TempName         string  `json:"temp_name"`
	Title            string  `json:"title"`
	Transcript       string  `json:"transcript"`
	UpdatedAt        string  `json:"updated_at"`
	URL              string  `json:"url"`
	UserID           int     `json:"user_id"`
	Words            int     `json:"words"`
	Workbook         string  `json:"workbook"`
	WorkbookFolderID int     `json:"workbook_folder_id"`
	WorkbookID       int     `json:"workbook_id"`
}

func (o *Data7) GetAudioType() string {
	if o == nil {
		return ""
	}
	return o.AudioType
}

func (o *Data7) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *Data7) GetDeletedAt() *string {
	if o == nil {
		return nil
	}
	return o.DeletedAt
}

func (o *Data7) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Data7) GetExpiresAt() string {
	if o == nil {
		return ""
	}
	return o.ExpiresAt
}

func (o *Data7) GetFileName() string {
	if o == nil {
		return ""
	}
	return o.FileName
}

func (o *Data7) GetFormat() string {
	if o == nil {
		return ""
	}
	return o.Format
}

func (o *Data7) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Data7) GetLength() string {
	if o == nil {
		return ""
	}
	return o.Length
}

func (o *Data7) GetPlanType() string {
	if o == nil {
		return ""
	}
	return o.PlanType
}

func (o *Data7) GetSize() string {
	if o == nil {
		return ""
	}
	return o.Size
}

func (o *Data7) GetStorage() string {
	if o == nil {
		return ""
	}
	return o.Storage
}

func (o *Data7) GetTask() string {
	if o == nil {
		return ""
	}
	return o.Task
}

func (o *Data7) GetTempName() string {
	if o == nil {
		return ""
	}
	return o.TempName
}

func (o *Data7) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *Data7) GetTranscript() string {
	if o == nil {
		return ""
	}
	return o.Transcript
}

func (o *Data7) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *Data7) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *Data7) GetUserID() int {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *Data7) GetWords() int {
	if o == nil {
		return 0
	}
	return o.Words
}

func (o *Data7) GetWorkbook() string {
	if o == nil {
		return ""
	}
	return o.Workbook
}

func (o *Data7) GetWorkbookFolderID() int {
	if o == nil {
		return 0
	}
	return o.WorkbookFolderID
}

func (o *Data7) GetWorkbookID() int {
	if o == nil {
		return 0
	}
	return o.WorkbookID
}
