// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Data10 struct {
	Category    string  `json:"category"`
	ChatCode    string  `json:"chat_code"`
	CreatedAt   string  `json:"created_at"`
	DeletedAt   *string `json:"deleted_at"`
	Description string  `json:"description"`
	ID          int     `json:"id"`
	Logo        string  `json:"logo"`
	Name        string  `json:"name"`
	Prompt      string  `json:"prompt"`
	Status      int     `json:"status"`
	SubName     string  `json:"sub_name"`
	Type        string  `json:"type"`
	UpdatedAt   string  `json:"updated_at"`
}

func (o *Data10) GetCategory() string {
	if o == nil {
		return ""
	}
	return o.Category
}

func (o *Data10) GetChatCode() string {
	if o == nil {
		return ""
	}
	return o.ChatCode
}

func (o *Data10) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *Data10) GetDeletedAt() *string {
	if o == nil {
		return nil
	}
	return o.DeletedAt
}

func (o *Data10) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *Data10) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Data10) GetLogo() string {
	if o == nil {
		return ""
	}
	return o.Logo
}

func (o *Data10) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Data10) GetPrompt() string {
	if o == nil {
		return ""
	}
	return o.Prompt
}

func (o *Data10) GetStatus() int {
	if o == nil {
		return 0
	}
	return o.Status
}

func (o *Data10) GetSubName() string {
	if o == nil {
		return ""
	}
	return o.SubName
}

func (o *Data10) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *Data10) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}
