// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Datum struct {
	CreatedAt    string  `json:"created_at"`
	Description  string  `json:"description"`
	Fields       string  `json:"fields"`
	Group        string  `json:"group"`
	Icon         string  `json:"icon"`
	ID           int     `json:"id"`
	Image        *string `json:"image"`
	Name         string  `json:"name"`
	New          int     `json:"new"`
	Package      string  `json:"package"`
	Popular      int     `json:"popular"`
	Professional int     `json:"professional"`
	Slug         string  `json:"slug"`
	Status       int     `json:"status"`
	TemplateCode string  `json:"template_code"`
	Type         string  `json:"type"`
	UpdatedAt    string  `json:"updated_at"`
}

func (o *Datum) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *Datum) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *Datum) GetFields() string {
	if o == nil {
		return ""
	}
	return o.Fields
}

func (o *Datum) GetGroup() string {
	if o == nil {
		return ""
	}
	return o.Group
}

func (o *Datum) GetIcon() string {
	if o == nil {
		return ""
	}
	return o.Icon
}

func (o *Datum) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Datum) GetImage() *string {
	if o == nil {
		return nil
	}
	return o.Image
}

func (o *Datum) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Datum) GetNew() int {
	if o == nil {
		return 0
	}
	return o.New
}

func (o *Datum) GetPackage() string {
	if o == nil {
		return ""
	}
	return o.Package
}

func (o *Datum) GetPopular() int {
	if o == nil {
		return 0
	}
	return o.Popular
}

func (o *Datum) GetProfessional() int {
	if o == nil {
		return 0
	}
	return o.Professional
}

func (o *Datum) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *Datum) GetStatus() int {
	if o == nil {
		return 0
	}
	return o.Status
}

func (o *Datum) GetTemplateCode() string {
	if o == nil {
		return ""
	}
	return o.TemplateCode
}

func (o *Datum) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *Datum) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}
