// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Field struct {
	Code        string `json:"code"`
	Input       string `json:"input"`
	Name        string `json:"name"`
	Placeholder string `json:"placeholder"`
}

func (o *Field) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *Field) GetInput() string {
	if o == nil {
		return ""
	}
	return o.Input
}

func (o *Field) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Field) GetPlaceholder() string {
	if o == nil {
		return ""
	}
	return o.Placeholder
}
