// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RolePivot struct {
	ModelID   int    `json:"model_id"`
	ModelType string `json:"model_type"`
	RoleID    int    `json:"role_id"`
}

func (o *RolePivot) GetModelID() int {
	if o == nil {
		return 0
	}
	return o.ModelID
}

func (o *RolePivot) GetModelType() string {
	if o == nil {
		return ""
	}
	return o.ModelType
}

func (o *RolePivot) GetRoleID() int {
	if o == nil {
		return 0
	}
	return o.RoleID
}

type Role struct {
	CreatedAt string    `json:"created_at"`
	GuardName string    `json:"guard_name"`
	ID        int       `json:"id"`
	Name      string    `json:"name"`
	Pivot     RolePivot `json:"pivot"`
	UpdatedAt string    `json:"updated_at"`
}

func (o *Role) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *Role) GetGuardName() string {
	if o == nil {
		return ""
	}
	return o.GuardName
}

func (o *Role) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Role) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Role) GetPivot() RolePivot {
	if o == nil {
		return RolePivot{}
	}
	return o.Pivot
}

func (o *Role) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}
